services:
  postgres:
    image: postgres:15-alpine
    container_name: seatsync-postgres
    environment:
      POSTGRES_DB: seatsync
      POSTGRES_USER: seatsync_user
      POSTGRES_PASSWORD: seatsync_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seatsync_user -d seatsync"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: seatsync-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@seatsync.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: 